#!/bin/bash
# Local APT Repository
# 2025 by simone at lisanet dot de
# License: BSD 2 clause - free to use, modify, and distribute

set -e

# --- functions ---
function check_dependencies() {
    local dependencies=("curl" "jq" "dpkg-scanpackages")
    for dep in "${dependencies[@]}"; do
        if ! command -v "$dep" &> /dev/null; then
            echo "❌  $dep is not installed. Please install it and try again."
            exit 1
        fi
    done
}

function log() {
  [ -z "$VERBOSE" ] && return
  echo "$1"
}

function usage() {
  echo "Usage: sudo update-localrepo [-v] [-c] [-h]"
  echo "  -v    Verbose output"
  echo "  -c    Clean the repository before updating"
  echo "  -h    Show this help message"
  exit 0
}

# --- main ---

VERBOSE=
CLEAN=
CONFIG_DIR="/etc/localrepo"
CONFIG_FILE="$CONFIG_DIR/packages.conf"
REPO_DIR="/usr/local/localrepo/"
REPO_FILE="/etc/apt/sources.list.d/localrepo.list"
DIST="stable"
CODENAME=$(lsb_release -cs)
_arch=$(dpkg --print-architecture)

# check for config
if [ ! -e "$CONFIG_FILE" ]; then
  echo "❌  No config file '$CONFIG_FILE' found."
  exit 1
fi

while [ "$#" -gt 0 ] ; do
  case "$1" in
    -v) VERBOSE="yes"
    ;;
    -c) CLEAN="yes"
    ;;
    -h) usage
    ;;
    *) echo "unknown parameter: $1"
      usage
      exit 1
    ;;
  esac
  shift
done


# Check for root privileges
if [[ $EUID -ne 0 ]]; then
   echo "❌  This script must be run with sudo."
   exit 1
fi

check_dependencies

# clean repo if requested
if [ "$CLEAN" == "yes" ]; then
    log "→ Cleaning local APT repository at $REPO_DIR"
    rm -rf "$REPO_DIR/dists" "$REPO_DIR/pool"
fi

log "→ Updating local APT repository at $REPO_DIR"

# create the apt pool dir
mkdir -p "$REPO_DIR/pool/amd64"
mkdir -p "$REPO_DIR/pool/all"
mkdir -p "$REPO_DIR/pool/armhf"
mkdir -p "$REPO_DIR/pool/arm64"

cd "$REPO_DIR/pool"
log "→ Processing packages from config: $CONFIG_FILE"
while read -r TYPE OWNER REPO ARCH PATTERN; do

    [[ "$TYPE" =~ ^#.*$ || -z "$TYPE" ]] && continue # Kommentar oder leer

    TYPE=$(echo "$TYPE" | tr '[:upper:]' '[:lower:]')
    if [ "$TYPE" == "script" ]; then
        # OWNER is the script name here
        log "→ Executing script $OWNER..."
        [ -x "$CONFIG_DIR/scripts/$OWNER" ] || { log "❌  Script $OWNER not executable or not found in $CONFIG_DIR/scripts"; continue; }
        URL=$("$CONFIG_DIR/scripts/$OWNER")
    elif [ "$TYPE" == "github" ]; then
        eval "PATTERN=$PATTERN"
        log "→ Fetching latest release from $OWNER/$REPO ($ARCH, pattern: $PATTERN)..."

        # get latest release
        URL=$(curl -s "https://api.github.com/repos/$OWNER/$REPO/releases/latest" \
            | jq -r --arg pat "$PATTERN" '.assets[] | select(.name | test($pat)) | .browser_download_url' | head -n 1)

        if [[ -z "$URL" ]]; then
            log "⚠️   No asset matching '$PATTERN' found for $OWNER/$REPO"
            continue
        fi
    else
        log "⚠️   Unknown type '$TYPE' in config, skipping."
        continue
    fi
    log "→ Download URL: $URL"

    DEB_FILE="${URL##*/}"
    if [ -f "$REPO_DIR/pool/$DEB_FILE" ]; then
        log "ℹ️   Lastest version already downloaded."
    else
        log "→ Downloading $DEB_FILE"
        cd "$REPO_DIR/pool/$ARCH"
        curl -s -LO "$URL"
    fi
done < "$CONFIG_FILE"

# build apt repo
log "→ Building APT repository..."
cd "$REPO_DIR"
for arch in amd64 all armhf arm64; do
    mkdir -p "$REPO_DIR/dists/$DIST/main/binary-$arch"
    dpkg-scanpackages "pool/$arch" | gzip -9c > "$REPO_DIR/dists/$DIST/main/binary-$arch/Packages.gz"
done

# generate sources.list
if [[ ! -f "$REPO_FILE" ]]; then
    log "→ Adding local APT source entry..."
    echo "deb [trusted=yes] file://$REPO_DIR $DIST main" > "$REPO_FILE"
fi

log "✅  Local APT repository ready."

